### ISSUE TITLE
Module build failed: Error: ENAMETOOLONG: name too long, open

### ISSUE THREAD

**Issue by sompylasar** [amireh/happypack#100]
`happypack@2.2.1`

```
./src/webapp/{CENSORED_99_CHARACTERS}.js
Module build failed: Error: ENAMETOOLONG: name too long, open '/srv/{CENSORED_12_CHARACTERS}/web/releases/2016-10-29_01.11.55.505_{CENSORED_44_CHARACTERS}_c5e6be8abb76159b09943383ae75854c536ea3b0/.happypack/_srv_{CENSORED_12_CHARACTERS}_web_releases_2016_10_29_01_11_55_505_{CENSORED_44_CHARACTERS}_c5e6be8abb76159b09943383ae75854c536ea3b0_src_webapp_{CENSORED_99_CHARACTERS}_js.map'
Error: ENAMETOOLONG: name too long, open '/srv/{CENSORED_12_CHARACTERS}/web/releases/2016-10-29_01.11.55.505_{CENSORED_44_CHARACTERS}_c5e6be8abb76159b09943383ae75854c536ea3b0/.happypack/_srv_{CENSORED_12_CHARACTERS}_web_releases_2016_10_29_01_11_55_505_{CENSORED_44_CHARACTERS}_c5e6be8abb76159b09943383ae75854c536ea3b0_src_webapp_{CENSORED_99_CHARACTERS}_js.map'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at /srv/{CENSORED_12_CHARACTERS}/web/releases/2016-10-29_01.11.55.505_{CENSORED_44_CHARACTERS}_c5e6be8abb76159b09943383ae75854c536ea3b0/node_modules/happypack/lib/HappyWorker.js:46:10
    at apply (/srv/{CENSORED_12_CHARACTERS}/web/releases/2016-10-29_01.11.55.505_{CENSORED_44_CHARACTERS}_c5e6be8abb76159b09943383ae75854c536ea3b0/node_modules/happypack/lib/applyLoaders.js:261:14)
    at /srv/{CENSORED_12_CHARACTERS}/web/releases/2016-10-29_01.11.55.505_{CENSORED_44_CHARACTERS}_c5e6be8abb76159b09943383ae75854c536ea3b0/node_modules/happypack/lib/applyLoaders.js:274:9
    at /srv/{CENSORED_12_CHARACTERS}/web/releases/2016-10-29_01.11.55.505_{CENSORED_44_CHARACTERS}_c5e6be8abb76159b09943383ae75854c536ea3b0/node_modules/happypack/lib/applyLoaders.js:330:17
    at Object.callback (/srv/{CENSORED_12_CHARACTERS}/web/releases/2016-10-29_01.11.55.505_{CENSORED_44_CHARACTERS}_c5e6be8abb76159b09943383ae75854c536ea3b0/node_modules/happypack/lib/fnOncePedantic.js:10:15)
    at Object.module.exports (/srv/{CENSORED_12_CHARACTERS}/web/releases/2016-10-29_01.11.55.505_{CENSORED_44_CHARACTERS}_c5e6be8abb76159b09943383ae75854c536ea3b0/node_modules/babel-loader/index.js:132:8)
    at applySyncOrAsync (/srv/{CENSORED_12_CHARACTERS}/web/releases/2016-10-29_01.11.55.505_{CENSORED_44_CHARACTERS}_c5e6be8abb76159b09943383ae75854c536ea3b0/node_modules/happypack/lib/applyLoaders.js:341:21)
    at /srv/{CENSORED_12_CHARACTERS}/web/releases/2016-10-29_01.11.55.505_{CENSORED_44_CHARACTERS}_c5e6be8abb76159b09943383ae75854c536ea3b0/node_modules/happypack/lib/HappyLoader.js:46:23
    at Object.Thread::1:2:1 (/srv/{CENSORED_12_CHARACTERS}/web/releases/2016-10-29_01.11.55.505_{CENSORED_44_CHARACTERS}_c5e6be8abb76159b09943383ae75854c536ea3b0/node_modules/happypack/lib/HappyPlugin.js:321:7)
    at ChildProcess.acceptMessageFromWorker (/srv/{CENSORED_12_CHARACTERS}/web/releases/2016-10-29_01.11.55.505_{CENSORED_44_CHARACTERS}_c5e6be8abb76159b09943383ae75854c536ea3b0/node_modules/happypack/lib/HappyThread.js:66:32)
    at emitTwo (events.js:92:20)
    at ChildProcess.emit (events.js:172:7)
    at internal/child_process.js:696:12
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

The filename exceeds `NAME_MAX` of `255` characters, it gets `257` characters long.

```
_srv_{CENSORED_12_CHARACTERS}_web_releases_2016_10_29_01_11_55_505_{CENSORED_44_CHARACTERS}_c5e6be8abb76159b09943383ae75854c536ea3b0_src_webapp_{CENSORED_99_CHARACTERS}_js.map
```

I suggest hashing the path to make the happypack filename, e.g. with `sha1`.

**Comment by sompylasar** [comment]
Weird, I've scanned `happypack@2.2.1` source code, `.happypack` is the default value of `tempDir`, the only thing it leads to is `compiledPath`, **but** `compiledPath` is built via hashing, not via string replacement.

```js
compiledPath: path.resolve(this.config.tempDir, HappyUtils.generateCompiledPath(filePath)),
```
```js
exports.generateCompiledPath = function(filePath) {
  return 's-' + hashString(filePath);
};
```

I've locally got a lot of files named like `.happypack/s--21689102` and `.happypack/s--21689102.map`. But on the build server I get the paths described above... Any ideas how this might happen?

**Comment by amireh** [comment]
Hmm, that function was revisited *after* 2.2.1. At 2.2.1 it looks like [this](https://github.com/amireh/happypack/blob/267dbc86fffe10896c2cf3e765daf3fadc0d180a/lib/HappyUtils.js#L5):

```javascript
exports.generateCompiledPath = function(filePath) {
  if (process.env.DEBUG) {
    return filePath.replace(/\W+/g, '_');
  }
  else {
    return 's-' + hashString(filePath);
  }
};
```

Which leads me to believe your environment has `DEBUG` exported... Either unset that environment variable (you can do that for the one process if you like, e.g. when invoking webpack, if your build needs it) or wait for the next release in which it's removed.

Sorry you're seeing this!

**Comment by sompylasar** [comment]
Oh, looks like the `2.2.1` in `package.json` of the latest `master` confused me. Yes, I've actually scanned [the latest master](https://github.com/amireh/happypack/tree/b27bc1f201d7b0f8057682018cb5646e9a056a2e).

I'll keep this open until the release is live, if you don't mind. Please post an update here when this happens.

Thanks!

**Comment by sompylasar** [comment]
@amireh More details on the case below.

We use https://github.com/visionmedia/debug where 
> The **DEBUG** environment variable is then used to enable these based on space or comma-delimited names.

So, this does not trigger the happypack `debug` flag default value:
```js
debug:                    { type: 'boolean', default: process.env.DEBUG === '1' },
```

but triggers the special behavior of `generateCompiledPath` [pointed out in the comment](https://github.com/amireh/happypack/issues/100#issuecomment-257105154) which does not use the `debug` flag, rather it uses `process.env.DEBUG` directly:
```js
exports.generateCompiledPath = function(filePath) {
  if (process.env.DEBUG) {
    return filePath.replace(/\W+/g, '_');
  }
  else {
    return 's-' + hashString(filePath);
  }
};
```

I've added a monkeypatch until this is fixed:
```js
// WORKAROUND(sompylasar): Monkeypatch `happypack@2.2.1` to fix `ENAMETOOLONG`. @see https://github.com/amireh/happypack/issues/100#issuecomment-257105154
// TODO(sompylasar): When the next version of `happypack` is released, remove this monkeypatch workaround.
const HappyUtils = require('happypack/lib/HappyUtils');
const HappyUtils_generateCompiledPath = HappyUtils.generateCompiledPath;  // eslint-disable-line camelcase
HappyUtils.generateCompiledPath = function (...args) {  // eslint-disable-line func-names
  // Store the original environment.
  const DEBUG_WAS_DEFINED = ('DEBUG' in process.env);
  const DEBUG = process.env.DEBUG;

  // `process.env.DEBUG` causes special long-filenames behavior in `generateCompiledPath` of `happypack@2.2.1`.
  delete process.env.DEBUG;

  const ret = HappyUtils_generateCompiledPath(...args);  // eslint-disable-line new-cap

  // Restore the environment.
  if (DEBUG_WAS_DEFINED) {
    process.env.DEBUG = DEBUG;
  }

  return ret;
};
```

**Comment by amireh** [comment]
This was fixed in the 3.0.0 release by the way. Please confirm so that we can close it.

**Comment by sompylasar** [comment]
@amireh Reviewed the code, looks like the special behavior on DEBUG has gone. Didn't test in the real world though. Thanks!

**Comment by amireh** [comment]
Closing this.
