### ISSUE TITLE
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin

### ISSUE THREAD

**Issue by shinygang** [amireh/happypack#102]
when I use `require('../assets/scss/sign.scss')` in my js file：it's has this error:
```
ERROR in ./src/assets/scss/sign.scss
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (/Users/tanggang/Desktop/yzj_work/cloudwork-social/frontend/node_modules/extract-text-webpack-plugin/loader.js:21:9)
    at applySyncOrAsync (/Users/tanggang/Desktop/yzj_work/cloudwork-social/frontend/node_modules/happypack/lib/applyLoaders.js:341:21)
    at applyPitchLoader (/Users/tanggang/Desktop/yzj_work/cloudwork-social/frontend/node_modules/happypack/lib/applyLoaders.js:201:7)
    at applyPitchLoaders (/Users/tanggang/Desktop/yzj_work/cloudwork-social/frontend/node_modules/happypack/lib/applyLoaders.js:222:4)
    at applyLoaders (/Users/tanggang/Desktop/yzj_work/cloudwork-social/frontend/node_modules/happypack/lib/applyLoaders.js:116:3)
    at HappyWorker.compile (/Users/tanggang/Desktop/yzj_work/cloudwork-social/frontend/node_modules/happypack/lib/HappyWorker.js:32:3)
    at process.accept (/Users/tanggang/Desktop/yzj_work/cloudwork-social/frontend/node_modules/happypack/lib/HappyWorkerChannel.js:24:14)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at /Users/tanggang/Desktop/yzj_work/cloudwork-social/frontend/node_modules/happypack/lib/HappyLoader.js:46:23
    at Object.Thread::0:1 (/Users/tanggang/Desktop/yzj_work/cloudwork-social/frontend/node_modules/happypack/lib/HappyPlugin.js:321:7)
    at ChildProcess.acceptMessageFromWorker (/Users/tanggang/Desktop/yzj_work/cloudwork-social/frontend/node_modules/happypack/lib/HappyThread.js:66:32)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./src/view/signin.js 15:0-35
```

**Comment by devlato** [comment]
I have faced the same problem previously, so I'm also interested in the solution.

**Comment by amireh** [comment]
Did you guys try the workaround in https://github.com/amireh/happypack/issues/14#issuecomment-208254692 ?

**Comment by amireh** [comment]
Closing since it's been almost a year
