### ISSUE TITLE
Less plugins throw error

### ISSUE THREAD

**Issue by zp1996** [amireh/happypack#187]
Hi, when i use happypack with less, such as:
```
var createHappyPlugin = function (id, loaders) {
    return new HappyPack({
        id: id,
        loaders: loaders,
        threadPool: HappyPack.ThreadPool({ size: os.cpus().length }),
        verbose: true
    });
};
```
create like:
```
        createHappyPlugin(
            'less',
            [
                'style-loader',
                {
                    loader: 'css-loader',
                    options: {
                        modules: true,
                        importLoaders: 1,
                        localIdentName: '[path][name]__[local]--[hash:base64:5]'
                    }
                },
                'postcss-loader',
                {
                     loader: 'less-loader',
                     strictImports: true,
                     options: {
                         plugins: [
                             new LessPluginFunctions()
                         ]
                     }
                }
            ]
        ),
```

it will throw error:
```
TypeError: plugin.install is not a function
```

**Comment by amireh** [comment]
It's postcss not less: you need to configure postcss in a separate file and point to that. See https://github.com/amireh/happypack/issues/84#issuecomment-257366444 for more information.

**Comment by zp1996** [comment]
Error like this:
```
Module build failed: TypeError: plugin.install is not a function
    at PluginManager.addPlugin (/Users/zp1996/alijk/fe/alihealth-h5-front-end/node_modules/_less@2.7.2@less/lib/less/plugin-manager.js:29:12)
    at PluginManager.addPlugins (/Users/zp1996/alijk/fe/alihealth-h5-front-end/node_modules/_less@2.7.2@less/lib/less/plugin-manager.js:19:18)
    at Object.parse (/Users/zp1996/alijk/fe/alihealth-h5-front-end/node_modules/_less@2.7.2@less/lib/less/parse.js:34:27)
    at Object.render (/Users/zp1996/alijk/fe/alihealth-h5-front-end/node_modules/_less@2.7.2@less/lib/less/render.js:25:18)
```

when i not use happypack, it work, but when i use happypack, throw this error
