### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated

### ISSUE THREAD

**Issue by dtothefp** [amireh/happypack#217]
Webpack: `v4.1.1`
Happypack: `v5.0.0-beta.1`
Node: `v8.1.3`

Running my webpack build with the `--trace-deprecation` I see that the deprecation warning 

```
(node:20108) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

Is related to Happypack plugin

```
(node:20108) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at HappyPlugin.apply (/Users/david.foxpowell/dev/sleep-spa-build/node_modules/happypack/lib/HappyPlugin.js:96:12)
    at webpack (/Users/david.foxpowell/dev/sleep-spa-build/node_modules/webpack/lib/webpack.js:37:12)
    at Promise (/Users/david.foxpowell/dev/sleep-spa-build/lib/tasks/webpack/index.js:23:26)
    at Promise (<anonymous>)
    at /Users/david.foxpowell/dev/sleep-spa-build/lib/tasks/webpack/index.js:20:12
    at Promise.resolve.then (/Users/david.foxpowell/dev/sleep-spa-build/lib/util/task.js:28:39)
```

**Comment by lerit** [comment]
same problem

**Comment by dtothefp** [comment]
looks like this is being tracked here https://github.com/amireh/happypack/issues/200#issuecomment-373699757
