### ISSUE TITLE
Error reporting in webpack4.5

### ISSUE THREAD

**Issue by yfjl** [amireh/happypack#222]
Error reporting in webpack4.5

**Comment by amireh** [comment]
Hi, please provide a proper report for us to be able to help:

- what issue you're having
- what you're expecting
- versions of webpack / happypack
- webpack config

**Comment by crayon-shin-chan** [comment]
``TypeError: Cannot read property 'watchRun' of undefined
    at setupWatchRun (/home/czy/桌面/react-demo/node_modules/awesome-typescript-loader/src/instance.ts:369:17)
    at Object.ensureInstance (/home/czy/桌面/react-demo/node_modules/awesome-typescript-loader/src/instance.ts:137:2)
    at compiler (/home/czy/桌面/react-demo/node_modules/awesome-typescript-loader/src/index.ts:47:19)
    at Object.loader (/home/czy/桌面/react-demo/node_modules/awesome-typescript-loader/src/index.ts:16:12)
    at applySyncOrAsync (/home/czy/桌面/react-demo/node_modules/happypack/lib/applyLoaders.js:350:21)
    at apply (/home/czy/桌面/react-demo/node_modules/happypack/lib/applyLoaders.js:277:5)
    at /home/czy/桌面/react-demo/node_modules/happypack/lib/applyLoaders.js:135:7
    at applyPitchLoader (/home/czy/桌面/react-demo/node_modules/happypack/lib/applyLoaders.js:188:14)
    at applyPitchLoader (/home/czy/桌面/react-demo/node_modules/happypack/lib/applyLoaders.js:196:14)
    at applyPitchLoaders (/home/czy/桌面/react-demo/node_modules/happypack/lib/applyLoaders.js:226:4) 'TypeError: Cannot read

**Comment by crayon-shin-chan** [comment]
it can not work with awesome-typescript-loader with webpack version is 4.5.0
