### ISSUE TITLE
[Webpack 4.5.0] TypeError: Cannot read property 'afterCompile' of undefined

### ISSUE THREAD

**Issue by jpz02** [amireh/happypack#224]
I'm getting a type error in webpack@4.5.0 using ts-loader@4.2.0 and babel-loader@7.1.4/8.0.0-beta.2 with happypack@5.0.0-beta.3

`
ERROR in ./frontend/js/boot.ts
    Module build failed: TypeError: Cannot read property 'afterCompile' of undefined
        at successfulTypeScriptInstance (/Users/XXXX/node_modules/ts-loader/dist/instances.js:167:28)
        at Object.getTypeScriptInstance (/Users/XXXX/node_modules/ts-loader/dist/instances.js:51:12)
        at Object.loader (/Users/XXXX/node_modules/ts-loader/dist/index.js:16:41)
        at applySyncOrAsync (/Users/XXXX/node_modules/happypack/lib/applyLoaders.js:350:21)
        at apply (/Users/XXXX/node_modules/happypack/lib/applyLoaders.js:277:5)
        at /Users/XXXX/node_modules/happypack/lib/applyLoaders.js:135:7
        at applyPitchLoader (/Users/XXXX/node_modules/happypack/lib/applyLoaders.js:188:14)
        at applyPitchLoader (/Users/XXXX/node_modules/happypack/lib/applyLoaders.js:196:14)
        at applyPitchLoader (/Users/XXXX/node_modules/happypack/lib/applyLoaders.js:196:14)
        at applyPitchLoaders (/Users/XXXX/node_modules/happypack/lib/applyLoaders.js:226:4)
`

the offending line in the ts-loader: 
`
loader._compiler.hooks.afterCompile.tapAsync('ts-loader', after_compile_1.makeAfterCompile(instance, configFilePath));
`

happy pack config:
`new HappyPack({
      loaders: [ 'babel-loader!ts-loader' ],
    }),
`

**Comment by jpz02** [comment]
happy pack config:
`new HappyPack({
      loaders: [ 'babel-loader!ts-loader' ],
    }),
`

**Comment by cjahv** [comment]
yes, this is my report
![image](https://user-images.githubusercontent.com/15372793/39029668-9a24d738-448f-11e8-9ba6-99d173421cca.png)
![image](https://user-images.githubusercontent.com/15372793/39029675-a108120e-448f-11e8-8c26-3a863b3af7b4.png)
I can't get hooks

**Comment by cjahv** [comment]
➜  hieip-client-ts git:(jahv) ✗ yarn list |grep happypack
├─ happypack@5.0.0-beta.3

**Comment by amireh** [comment]
I'm fairly certain you need to pass `?happyPackMode=true` to `ts-loader` for it to work in a parallel environment. See their documentation on the option: https://github.com/TypeStrong/ts-loader#happypackmode-boolean-defaultfalse

**Comment by jpz02** [comment]
Yeah I’m pretty sure it was. I found out about the happypack mode whilst I was working through the errors, but I had made changes to loader chaining and didn’t think anything of it. Cheers.
