### ISSUE TITLE
Happypack with @ngtools/webpack

### ISSUE THREAD

**Issue by AlexanderLea** [amireh/happypack#228]
Hi,

We have a production (using @ngtools/webpack for AOT) build, working fine using Webpack, but it takes a long time.

Looking at implementing Happypack in our webpack.prod config, and it looks like it is is working (get the happy[html] output, and then the child outputs from webpack as normal, but it also throws an error:

`ERROR in ./ClientApp/main-aot.ts
Module build failed: TypeError: Cannot read property '_ngToolsWebpackPluginInstance' of undefined
    at Object.ngcLoader ($$$filepath$$$\node_modules\@ngtools\webpack\src\loader.js:425:37)
    at applySyncOrAsync ($$$filepath$$$\node_modules\happypack\lib\applyLoaders.js:350:21)
    at apply ($$$filepath$$$\node_modules\happypack\lib\applyLoaders.js:277:5)
    at $$$filepath$$$\node_modules\happypack\lib\applyLoaders.js:135:7
    at applyPitchLoader ($$$filepath$$$\node_modules\happypack\lib\applyLoaders.js:188:14)
    at applyPitchLoader ($$$filepath$$$\node_modules\happypack\lib\applyLoaders.js:196:14)
    at applyPitchLoaders ($$$filepath$$$\node_modules\happypack\lib\applyLoaders.js:226:4)
    at applyLoaders ($$$filepath$$$\node_modules\happypack\lib\applyLoaders.js:120:3)
    at HappyWorker.compile ($$$filepath$$$\node_modules\happypack\lib\HappyWorker.js:27:3)
    at COMPILE ($$$filepath$$$\node_modules\happypack\lib\HappyWorkerChannel.js:46:10)

ERROR in ./ClientApp/polyfills.ts
Module build failed: TypeError: Cannot read property '_ngToolsWebpackPluginInstance' of undefined
    at Object.ngcLoader ($$$filepath$$$\node_modules\@ngtools\webpack\src\loader.js:425:37)
    at applySyncOrAsync ($$$filepath$$$\node_modules\happypack\lib\applyLoaders.js:350:21)
    at apply ($$$filepath$$$\node_modules\happypack\lib\applyLoaders.js:277:5)
    at $$$filepath$$$\node_modules\happypack\lib\applyLoaders.js:135:7
    at applyPitchLoader ($$$filepath$$$\node_modules\happypack\lib\applyLoaders.js:188:14)
    at applyPitchLoader ($$$filepath$$$\node_modules\happypack\lib\applyLoaders.js:196:14)
    at applyPitchLoaders ($$$filepath$$$\node_modules\happypack\lib\applyLoaders.js:226:4)
    at applyLoaders ($$$filepath$$$\node_modules\happypack\lib\applyLoaders.js:120:3)
    at HappyWorker.compile ($$$filepath$$$\node_modules\happypack\lib\HappyWorker.js:27:3)
    at COMPILE ($$$filepath$$$\node_modules\happypack\lib\HappyWorkerChannel.js:46:10)

ERROR in ./ClientApp/vendor.ts
Module build failed: TypeError: Cannot read property '_ngToolsWebpackPluginInstance' of undefined
    at Object.ngcLoader ($$$filepath$$$\node_modules\@ngtools\webpack\src\loader.js:425:37)
    at applySyncOrAsync ($$$filepath$$$\node_modules\happypack\lib\applyLoaders.js:350:21)
    at apply ($$$filepath$$$\node_modules\happypack\lib\applyLoaders.js:277:5)
    at $$$filepath$$$\node_modules\happypack\lib\applyLoaders.js:135:7
    at applyPitchLoader ($$$filepath$$$\node_modules\happypack\lib\applyLoaders.js:188:14)
    at applyPitchLoader ($$$filepath$$$\node_modules\happypack\lib\applyLoaders.js:196:14)
    at applyPitchLoaders ($$$filepath$$$\node_modules\happypack\lib\applyLoaders.js:226:4)
    at applyLoaders ($$$filepath$$$\node_modules\happypack\lib\applyLoaders.js:120:3)
    at HappyWorker.compile ($$$filepath$$$\node_modules\happypack\lib\HappyWorker.js:27:3)
    at COMPILE ($$$filepath$$$\node_modules\happypack\lib\HappyWorkerChannel.js:46:10)

ERROR in window is not defined

I notice that @ngtools/webpack isn't in the list of compatible libraries, and I imagine that this is my issue.

Any help would be appreciated.

**Comment by bfrontend** [comment]
![image](https://user-images.githubusercontent.com/40289489/87514976-b403a100-c6ad-11ea-83c4-1df22f7fd5ef.png)
I have a similar problem. Have you solved it
