### ISSUE TITLE
webpack2 support

### ISSUE THREAD

**Issue by beckend** [amireh/happypack#23]
Gave it a spin:
```
Error: Signature changed: context parameter added
    at Tapable.resolve (/Users/beckend/Coding/test/node_modules/enhanced-resolve/lib/Resolver.js:30:9)
    at /Users/beckend/Coding/test/node_modules/happypack/lib/WebpackUtils.js:22:33
    at /Users/beckend/Coding/test/node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (/Users/beckend/Coding/test/node_modules/async/lib/async.js:233:13)
    at _parallel (/Users/beckend/Coding/test/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/Users/beckend/Coding/test/node_modules/async/lib/async.js:731:9)
    at Object.exports.resolveLoaders (/Users/beckend/Coding/test/node_modules/happypack/lib/WebpackUtils.js:19:9)
    at resolveLoaders (/Users/beckend/Coding/test/node_modules/happypack/lib/HappyPlugin.js:181:20)
    at /Users/beckend/Coding/test/node_modules/async/lib/async.js:718:13
    at Immediate.iterate [as _onImmediate] (/Users/beckend/Coding/test/node_modules/async/lib/async.js:262:13)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by amireh** [comment]
It should be functional now, had to make a small adjustment. Release 2.0.3 should work, if not, feel free to re-open.
