### ISSUE TITLE
Stylus-relative-loader and Eslint-loader support

### ISSUE THREAD

**Issue by ephor** [amireh/happypack#78]
Hello! I have a problem with stylus-relative-loader. I am trying to use this settings https://github.com/amireh/happypack/issues/14#issuecomment-208254692, but not working, and i got this error:

```
Module parse failed: /home/*****/*****/********/node_modules/happypack/loader.js?id=stylus!/home/****/*****/****/*****/styl/public/********.styl Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.
```

I am using stylus define, and it is also not working. Maybe I am doing something wrong, but I can't understand what exactly.

My config:
```
var webpack = require('webpack');
const path = require('path');

const ExtractTextPlugin = require("extract-text-webpack-plugin");

var HappyPack = require('happypack');
var happyThreadPool = HappyPack.ThreadPool({ size: 5 });

const entries = {
    'portable.styl': 'bundles/stylus_bundles/***.js',
};

module.exports = {
    entry,
    output: {
        path: 'public/js/stylus_build/',
        filename: '[name]/[name]_styl.js',
    },
    module: {
        loaders: [
            {
                test: /\.styl$/,
                loader: ExtractTextPlugin.extract('style', 'happypack/loader?id=stylus'),
            }
        ],
    },
    devtool: false,
    plugins: [
        new ExtractTextPlugin('../../css/[name].css', {
            allChunks: true
        }),
        createHappyPlugin('stylus', [ 'stylus-relative-loader?resolve url' ]),
    ],
    resolve: {
        modulesDirectories: [
            path.resolve(__dirname, 'styl'),
            path.resolve(__dirname, 'cs'),
        ],
        extensions: ['.js', '.styl', ''],
    },
    stylus: {
        define: {
            'http_fonts_dir': '/fonts/',
            'http_images_dir': '/image/'
        },
    }
};


function createHappyPlugin(id, loaders) {
  return new HappyPack({
    id: id,
    loaders: loaders,
    threadPool: happyThreadPool,

    // disable happy caching with HAPPY_CACHE=0
    cache: process.env.HAPPY_CACHE !== '0',

    // make happy more verbose with HAPPY_VERBOSE=1
    verbose: process.env.HAPPY_VERBOSE === '1',
  });
}
```

I would also ask about Eslint-loader. Is it possible to speed up its work? Because it is very slow (72seconds with eslint and 36 without), and make it work with Happypack fails

**Comment by amireh** [comment]
> I would also ask about Eslint-loader. Is it possible to speed up its work? Because it is very slow (72seconds with eslint and 36 without), and make it work with Happypack fails

The thing about eslint-loader and (other lint loaders like tslint-loader) is that their output is in the form of warnings and not source code / source maps. HappyPack should work for them (in theory) only as long as there's no cache because we don't "replay" those warnings when a cached file is found. So if a file gets cached and it had linter warnings, the next time you pick it up, the warnings won't show up.

We can fix that but I just didn't find the time to do it yet.

About your main problem, it could be something with the loader itself. I'll check out its source and get back to you.

**Comment by amireh** [comment]
Ok, one thing I notice in the config is that you're exposing a `stylus` attribute. _Maybe_ try telling happypack that it should export this and see if it helps (because it exports only a whitelist of compiler attributes to child workers, see https://github.com/amireh/happypack/blob/master/lib/HappyPlugin.js#L339)

Something like this:

```javascript
var HappyPack = require('happypack');
HappyPack.SERIALIZABLE_OPTIONS.push('stylus');
```

**Comment by ephor** [comment]
Thank you for answer about eslint-loader!

**Comment by ephor** [comment]
Good afternoon! Did you check the loader?

**Comment by amireh** [comment]
Hello, I'm sorry I didn't get the chance to visit happypack issues for weeks now as I'm finding no time at all. Perhaps the coming weekend will be different in which case I'll update the ticket.

However, you never really explained how the loader "fails". Can you clarify a bit?

Thanks!

**Comment by ephor** [comment]
Hello, I got this error
```
    ERROR in ./~/happypack/loader.js?id=stylus!./styl/public/mobile/mobile_theme_red.styl
    Module parse failed: *****/node_modules/happypack/loader.js?id=stylus!*****/styl/public/mobile/mobile_theme_red Unexpected token (39:0)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token (39:0)
        at Parser.pp$4.raise (*****/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
        at Parser.pp.unexpected (*****/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
        at Parser.pp$3.parseExprAtom (*****/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
        at Parser.pp$3.parseExprSubscripts (*****/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
        at Parser.pp$3.parseMaybeUnary (*****/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
        at Parser.pp$3.parseExprOps (*****/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
        at Parser.pp$3.parseMaybeConditional (*****/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
        at Parser.pp$3.parseMaybeAssign (*****/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
        at Parser.pp$3.parseExpression (*****/node_modules/webpack/node_modules/acorn/dist/acorn.js:1577:63)
        at Parser.pp$1.parseStatement (*****/node_modules/webpack/node_modules/acorn/dist/acorn.js:727:47)
        at Parser.pp$1.parseTopLevel (*****/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
        at Parser.parse (*****/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
        at Object.parse (*****/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
        at Parser.parse (*****/node_modules/webpack/lib/Parser.js:902:15)
        at DependenciesBlock.<anonymous> (*****/node_modules/webpack/lib/NormalModule.js:104:16)
        at DependenciesBlock.onModuleBuild (*****/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
        at nextLoader (*****/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
        at *****/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
        at context.callback (*****/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
        at *****/node_modules/happypack/lib/HappyLoader.js:49:5
        at HappyPlugin.compileInBackground (*****/node_modules/happypack/lib/HappyPlugin.js:273:12)
        at HappyPlugin.compile (*****/node_modules/happypack/lib/HappyPlugin.js:262:17)
        at Object.HappyLoader (*****/node_modules/happypack/lib/HappyLoader.js:27:15)
        at WEBPACK_CORE_LOADER_EXECUTION (*****/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
        at runSyncOrAsync (*****/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
        at nextLoader (*****/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
        at *****/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
        at Storage.finished (*****/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
        at *****/node_modules/graceful-fs/graceful-fs.js:78:16
        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)

```

**Comment by ephor** [comment]
omg. I add `css!` to createHappyPlugin('stylus', [ 'css!stylus-relative-loader?resolve url' ]), and it works.

**Comment by amireh** [comment]
Curious, did you _not_ need to use the `css-loader` without happypack? Or was this just something you missed when you configured happypack?

**Comment by ephor** [comment]
Yes, I do not need `css-loader` without happypack. And one more thing) When I type ` webpack --progress -p`,  css is not minify

**Comment by Strate** [comment]
I can't get to work distributed build of stylus + css, this is example comfiguration:
```js
module.exports = {
  loaders: [
    {
          test: /\.styl$/,
          include: srcDir,
          loaders: [
            "style-loader",
            "happypack/loader?id=cssStylus"
          ],
        },
  ],
  plugins: [
    new HappyPack({
      loaders: [
        "css",
        "stylus"
      ]
    })
  ]
}
```

This configuration produces exatly the same error, as described at https://github.com/amireh/happypack/issues/78#issuecomment-246599510

**Comment by ephor** [comment]
@Strate try to use my config, but with createHappyPlugin('stylus', [ '**_css!_**stylus-relative-loader?resolve url' ]),
